# Generated by Django 3.0.6 on 2020-05-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200510_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='zipcode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.ZipCode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='adress',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='StreetType',
        ),
    ]
