# Generated by Django 3.0.6 on 2020-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200511_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='postale_code',
            field=models.CharField(default=' ', max_length=6, verbose_name='Code postale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkcommande',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adress',
            field=models.CharField(max_length=1000, verbose_name='Adresse postale'),
        ),
    ]
