# Generated by Django 3.0.6 on 2020-05-14 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200514_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcommande',
            name='date',
        ),
        migrations.RemoveField(
            model_name='linkcommande',
            name='profil',
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 16, 2, 54, 285130, tzinfo=utc))),
                ('status', models.CharField(choices=[('ICT', 'in creation'), ('IPP', 'in preparation'), ('IPG', 'in progress'), ('DEL', 'delivered')], default='ICT', max_length=3)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='linkcommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Commande'),
        ),
    ]
